config/routes.rb
Rails.application.routes.draw do
  resources :distances

  root 'distances#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/distance.rb
class Distance < ApplicationRecord
    geocoded_by :start_address
    geocoded_by :destination_address
    reverse_geocoded_by :latitude, :longitude
    after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController
  before_action :set_distance, only: [:show, :edit, :update, :destroy]
  def index
    @distances = Distance.all
  end

  def new
    @distance = Distance.new
  end

  # Convert total minutes to hours and minutes
  def formatted_duration(total_minute)
    hours = (total_minute / 60).round
    minutes = ((total_minute) % 60).round
    "#{ hours }h #{ minutes }min"
  end

  def create
    @distance = Distance.new(distance_params)

    # Query the GoogleAPI to get distance and time from start and destination addresses
    directions = GoogleDirections.new(@distance.start_address, @distance.destination_address)
    @distance.miles = Geocoder::Calculations.distance_between(@distance.start_address, @distance.destination_address).round(2)
    @distance.time = formatted_duration(directions.drive_time_in_minutes)


    # If query fails to generate travel time, approximate it with flight speed
    # NOTE: needs better solution
    if directions.drive_time_in_minutes == 0
      total_mins = ((@distance.miles/460)*60)
      @distance.time = formatted_duration(total_mins)
    end

    respond_to do |format|
      if @distance.save
        format.html { redirect_to root_path, notice: 'Distance was successfully created.' }
        format.json { render :show, status: :created, location: @distance }
      else
        format.html { render :new }
        format.json { render json: @distance.errors, status: :unprocessable_entity }
      end
    end
  end

  # Destroy a single destination calculation
  def destroy
    @distance.destroy
    respond_to do |format|
      format.html { redirect_to distances_url, notice: 'Distance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distance
      @distance = Distance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distance_params
      params.require(:distance).permit(:latitude, :longitude, :start_address, :destination_address, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/views/distances/_form.html.erb
<%= form_for(@distance, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @distance.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@distance.errors.count, "error") %> prohibited this distance from being saved:</h4>

      <ul>
      <% @distance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :start_address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :start_address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :destination_address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :destination_address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/distances/edit.html.erb
<div class="page-header">
  <%= link_to distances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @distance, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing distance</h1>
</div>

<%= render 'form' %>

app/views/distances/index.html.erb
<div class="page-header">
  <%= link_to new_distance_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Distance
  <% end %>
  <h1>Listing distances</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Start Address</th>
        <th>Destination Address</th>
        <th>Distance(Miles)</th>
        <th>Driving Distance(Time)</th>
        <th></th>
      </tr>
    </thead>

    <!-- List out all saved destinations and distances -->
    <tbody>
      <%= content_tag_for(:tr, @distances) do |distance| %>
        <td><%= distance.start_address %></td>
        <td><%= distance.destination_address %></td>
        <td><%= distance.miles %> Mile(s) </td>
        <td><%= distance.time %> </td>
        <td><%= link_to 'Delete', distance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/distances/new.html.erb
<div class="page-header">
  <%= link_to distances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New distance</h1>
</div>

<%= render 'form' %>

app/views/distances/show.html.erb
<div class="page-header">
  <%= link_to distances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_distance_path(@distance), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show distance</h1>
</div>

<dl class="dl-horizontal">
  <dt>Start address:</dt>
  <dd><%= @distance.start_address %></dd>

  <dt>Destination address:</dt>
  <dd><%= @distance.destination_address %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Location Distance Calculator</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Location Distance Calculator", root_path, class: "navbar-brand" %>
      </div>
      <!-- <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
        </ul>
      </div> -->
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>